sudo: required

services:
  - docker

script:
  - docker-compose run app /bin/bash -c "cd /src && npm test"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag haarapi_app stuartalexwhitehead/haar-api
  - docker push stuartalexwhitehead/haar-api